In [1]:
#! pip install -U climetlab --quiet
#! pip install -U climetlab_s2s_ai_challenge --quiet

In [ ]:
import climetlab as cml 

In [3]:
import climetlab_s2s_ai_challenge
print(f'Climetlab version : {cml.__version__}')
print(f'Climetlab-s2s-ai-challenge plugin version : {climetlab_s2s_ai_challenge.__version__}')

Climetlab version : 0.5.4
Climetlab-s2s-ai-challenge plugin version : 0.4.13


In [4]:
import os
# When running in continous integration in github,
# append "-dev" to the datasets name to download only a fragment of data
# Warning : do not use the "-dev" datasets for training ML models.
if os.environ.get('GITHUB_ACTIONS'):
    is_test = '-dev'
else:
    is_test = ''

# Using grib data

In [5]:
FORMAT = 'grib'

Let us download netcdf file for total precipitation (tp) for one given date from the training-input dataset :

In [6]:
cmlds = cml.load_dataset("s2s-ai-challenge-training-input"+is_test,
                         origin='ecmwf',
                         date=20200102,
                         parameter='tp',
                         format=FORMAT)

By downloading data from this dataset, you agree to the terms and conditions defined at https://apps.ecmwf.int/datasets/data/s2s/licence/. If you do not agree with such terms, do not download the data. 


We can iterate on the list of grib data:

In [7]:
for field in list(cmlds)[0:2]:
    print(field)
    print(field.valid_datetime(), field.shape)
    print(field.to_numpy())

GribField(tp,None,20200102,0,0,0)
2020-01-02 00:00:00 (121, 240)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
GribField(tp,None,20200102,0,24,0)
2020-01-03 00:00:00 (121, 240)
[[0.3046875  0.3046875  0.3046875  ... 0.3046875  0.3046875  0.3046875 ]
 [0.28125    0.28125    0.28515625 ... 0.28515625 0.28515625 0.28125   ]
 [0.58203125 0.5703125  0.5546875  ... 0.64453125 0.62890625 0.60546875]
 ...
 [0.         0.         0.         ... 0.0078125  0.0078125  0.00390625]
 [0.0078125  0.0078125  0.0078125  ... 0.01171875 0.01171875 0.0078125 ]
 [0.0859375  0.0859375  0.0859375  ... 0.0859375  0.0859375  0.0859375 ]]


This climetlab dataset can be used as a xarray.Dataset or as a pandas.DataFrame :

In [8]:
cmlds.to_xarray()

<xarray.Dataset>
Dimensions:        (forecast_time: 20, latitude: 121, lead_time: 47, longitude: 240, realization: 11)
Coordinates:
  * realization    (realization) int64 0 1 2 3 4 5 6 7 8 9 10
  * forecast_time  (forecast_time) datetime64[ns] 2000-01-02 ... 2019-01-02
  * lead_time      (lead_time) timedelta64[ns] 0 days 1 days ... 45 days 46 days
  * latitude       (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * longitude      (longitude) float64 0.0 1.5 3.0 4.5 ... 355.5 357.0 358.5
    valid_time     (forecast_time, lead_time) datetime64[ns] dask.array<chunksize=(1, 1), meta=np.ndarray>
Data variables:
    tp             (realization, forecast_time, lead_time, latitude, longitude) float32 dask.array<chunksize=(1, 1, 1, 121, 240), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2021-04-27T13:03:41 GRIB to CDM+CF via cfgrib-0....

We can get the temperature parameter (2t) in a similar fashion. The "date" and "parameter" arguments also accept lists of values.

In [9]:
cml.load_dataset("s2s-ai-challenge-training-input"+is_test,
                         origin='ecmwf',
                         date=20200102,
                         parameter='2t',
                         format=FORMAT).to_xarray()

<xarray.Dataset>
Dimensions:        (forecast_time: 20, latitude: 121, lead_time: 46, longitude: 240, realization: 11)
Coordinates:
  * realization    (realization) int64 0 1 2 3 4 5 6 7 8 9 10
  * forecast_time  (forecast_time) datetime64[ns] 2000-01-02 ... 2019-01-02
  * lead_time      (lead_time) timedelta64[ns] 1 days 2 days ... 45 days 46 days
  * latitude       (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * longitude      (longitude) float64 0.0 1.5 3.0 4.5 ... 355.5 357.0 358.5
    valid_time     (forecast_time, lead_time) datetime64[ns] dask.array<chunksize=(1, 1), meta=np.ndarray>
Data variables:
    t2m            (realization, forecast_time, lead_time, latitude, longitude) float32 dask.array<chunksize=(1, 1, 1, 121, 240), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2021-04-27T13:03:48 GRIB to CDM+CF via cfgrib-0....

In [10]:
#import numpy as np
#dates = [np.datetime64('2020-01-02'),'2020-01-09']#,'20200116']
#cml.load_dataset("s2s-ai-challenge-training-input",
#                 origin='eccc',
#                 date=dates,
#                 parameter=['2t','tp'],
#                 format=FORMAT).to_xarray()                 

Data from the forecast-input dataset can be retrieve in a similar fashion:

In [11]:
cml.load_dataset("s2s-ai-challenge-forecast-input"+is_test,
                         origin='ecmwf',
                         date=["20200102","20200109"],
                         parameter='2t',
                         format=FORMAT).to_xarray()

By downloading data from this dataset, you agree to the terms and conditions defined at https://apps.ecmwf.int/datasets/data/s2s/licence/. If you do not agree with such terms, do not download the data. 


/home/mafp/.local/lib/python3.8/site-packages/dask/array/core.py:4241: PerformanceWarning: Increasing number of chunks by factor of 46
  result = blockwise(
/home/mafp/.local/lib/python3.8/site-packages/dask/array/core.py:4241: PerformanceWarning: Increasing number of chunks by factor of 46
  result = blockwise(


<xarray.Dataset>
Dimensions:        (forecast_time: 2, latitude: 121, lead_time: 46, longitude: 240, realization: 51)
Coordinates:
  * forecast_time  (forecast_time) datetime64[ns] 2020-01-02 2020-01-09
  * realization    (realization) int64 0 1 2 3 4 5 6 7 ... 44 45 46 47 48 49 50
  * lead_time      (lead_time) timedelta64[ns] 1 days 2 days ... 45 days 46 days
  * latitude       (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * longitude      (longitude) float64 0.0 1.5 3.0 4.5 ... 355.5 357.0 358.5
    valid_time     (forecast_time, lead_time) datetime64[ns] dask.array<chunksize=(2, 1), meta=np.ndarray>
Data variables:
    t2m            (realization, forecast_time, lead_time, latitude, longitude) float32 dask.array<chunksize=(1, 2, 1, 121, 240), meta=np.ndarray>

### Computing average and plotting

In [12]:
ds = cml.load_dataset("s2s-ai-challenge-forecast-input"+is_test,
                         origin='ecmwf',
                         date=["20200102","20200109"],
                         parameter='2t',
                         format=FORMAT).to_xarray()

/home/mafp/.local/lib/python3.8/site-packages/dask/array/core.py:4241: PerformanceWarning: Increasing number of chunks by factor of 46
  result = blockwise(
/home/mafp/.local/lib/python3.8/site-packages/dask/array/core.py:4241: PerformanceWarning: Increasing number of chunks by factor of 46
  result = blockwise(


In [13]:
mean1 = ds.mean(dim="lead_time")
mean1.compute()
#cml.plot_map(mean1.isel(forecast_time=0, realization=0))

<xarray.Dataset>
Dimensions:        (forecast_time: 2, latitude: 121, longitude: 240, realization: 51)
Coordinates:
  * forecast_time  (forecast_time) datetime64[ns] 2020-01-02 2020-01-09
  * realization    (realization) int64 0 1 2 3 4 5 6 7 ... 44 45 46 47 48 49 50
  * latitude       (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * longitude      (longitude) float64 0.0 1.5 3.0 4.5 ... 355.5 357.0 358.5
Data variables:
    t2m            (realization, forecast_time, latitude, longitude) float32 ...

In [14]:
mean2 = ds.mean(dim="forecast_time")
mean2.compute()
#cml.plot_map(mean2.isel(lead_time=2, realization=0))

<xarray.Dataset>
Dimensions:      (latitude: 121, lead_time: 46, longitude: 240, realization: 51)
Coordinates:
  * realization  (realization) int64 0 1 2 3 4 5 6 7 ... 43 44 45 46 47 48 49 50
  * lead_time    (lead_time) timedelta64[ns] 1 days 2 days ... 45 days 46 days
  * latitude     (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * longitude    (longitude) float64 0.0 1.5 3.0 4.5 ... 354.0 355.5 357.0 358.5
Data variables:
    t2m          (realization, lead_time, latitude, longitude) float32 246.4 ...

In [15]:
mean3 = ds[['t2m','valid_time']].groupby('valid_time').mean()['t2m']
mean3.compute()
# cml.plot_map(mean3.isel(forecast_time=2, realization=0))

<xarray.DataArray 't2m' (valid_time: 53, realization: 51, latitude: 121, longitude: 240)>
array([[[[244.4057 , 244.4057 , 244.4057 , ..., 244.4057 , 244.4057 ,
          244.4057 ],
         [243.81586, 243.80609, 243.79242, ..., 243.8764 , 243.85687,
          243.83539],
         [243.9682 , 243.87445, 243.76312, ..., 244.11859, 244.05023,
          244.00531],
         ...,
         [248.26312, 248.21234, 248.14789, ..., 247.9975 , 248.10297,
          248.1889 ],
         [247.56   , 247.5346 , 247.50726, ..., 247.55219, 247.55609,
          247.56   ],
         [245.935  , 245.935  , 245.935  , ..., 245.935  , 245.935  ,
          245.935  ]],

        [[244.53333, 244.53333, 244.53333, ..., 244.53333, 244.53333,
          244.53333],
         [244.03333, 244.0177 , 244.00012, ..., 244.12317, 244.09387,
          244.06458],
         [244.06848, 243.95715, 243.83997, ..., 244.2345 , 244.17004,
          244.11536],
...
         [234.17163, 233.97437, 233.781  , ..., 234.53687, 234.41382,
          234.29077],
         [233.99976, 233.97046, 233.94116, ..., 233.98413, 233.98999,
          233.99585],
         [231.9021 , 231.9021 , 231.9021 , ..., 231.9021 , 231.9021 ,
          231.9021 ]],

        [[249.77338, 249.77338, 249.77338, ..., 249.77338, 249.77338,
          249.77338],
         [249.87885, 249.88861, 249.89838, ..., 249.83783, 249.8515 ,
          249.86517],
         [249.67963, 249.70697, 249.73236, ..., 249.81049, 249.76752,
          249.72455],
         ...,
         [230.30267, 230.2851 , 230.27142, ..., 230.29486, 230.29681,
          230.30072],
         [229.41205, 229.4472 , 229.48041, ..., 229.31439, 229.3476 ,
          229.3808 ],
         [229.83392, 229.83392, 229.83392, ..., 229.83392, 229.83392,
          229.83392]]]], dtype=float32)
Coordinates:
  * realization  (realization) int64 0 1 2 3 4 5 6 7 ... 43 44 45 46 47 48 49 50
  * latitude     (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * longitude    (longitude) float64 0.0 1.5 3.0 4.5 ... 354.0 355.5 357.0 358.5
  * valid_time   (valid_time) datetime64[ns] 2020-01-03 ... 2020-02-24