In [1]:
#! pip install -U climetlab --quiet
#! pip install -U climetlab_s2s_ai_challenge --quiet

In [ ]:
import climetlab as cml 

In [3]:
import climetlab_s2s_ai_challenge
print(f'Climetlab version : {cml.__version__}')
print(f'Climetlab-s2s-ai-challenge plugin version : {climetlab_s2s_ai_challenge.__version__}')

Climetlab version : 0.5.3
Climetlab-s2s-ai-challenge plugin version : 0.4.12


# Using grib data

In [4]:
FORMAT = 'grib'

Let us download netcdf file for total precipitation (tp) for one given date from the training-input dataset :

In [5]:
cmlds = cml.load_dataset("s2s-ai-challenge-training-input",
                         origin='ecmwf',
                         date=20200102,
                         parameter='tp',
                         format=FORMAT)

By downloading data from this dataset, you agree to the terms and conditions defined at https://apps.ecmwf.int/datasets/data/s2s/licence/. If you do not agree with such terms, do not download the data. 


We can iterate on the list of grib data:

In [14]:
for field in list(cmlds)[0:2]:
    print(field)
    print(field.valid_datetime(), field.shape)
    print(field.to_numpy())

GribField(tp,None,20200102,0,24,0)
2020-01-03 00:00:00 (121, 240)
[[0.3046875  0.3046875  0.3046875  ... 0.3046875  0.3046875  0.3046875 ]
 [0.28125    0.28125    0.28515625 ... 0.28515625 0.28515625 0.28125   ]
 [0.58203125 0.5703125  0.5546875  ... 0.64453125 0.62890625 0.60546875]
 ...
 [0.         0.         0.         ... 0.0078125  0.0078125  0.00390625]
 [0.0078125  0.0078125  0.0078125  ... 0.01171875 0.01171875 0.0078125 ]
 [0.0859375  0.0859375  0.0859375  ... 0.0859375  0.0859375  0.0859375 ]]
GribField(tp,None,20200102,0,48,0)
2020-01-04 00:00:00 (121, 240)
[[0.9375    0.9375    0.9375    ... 0.9375    0.9375    0.9375   ]
 [1.0546875 1.0546875 1.046875  ... 1.09375   1.0859375 1.0703125]
 [1.46875   1.46875   1.46875   ... 1.5546875 1.515625  1.5      ]
 ...
 [0.        0.        0.        ... 0.0078125 0.0078125 0.       ]
 [0.0078125 0.0078125 0.0078125 ... 0.015625  0.0078125 0.0078125]
 [0.203125  0.203125  0.203125  ... 0.203125  0.203125  0.203125 ]]


This climetlab dataset can be used as a xarray.Dataset or as a pandas.DataFrame :

In [6]:
cmlds.to_xarray()

<xarray.Dataset>
Dimensions:        (forecast_time: 20, latitude: 121, lead_time: 3, longitude: 240, realization: 2)
Coordinates:
  * realization    (realization) int64 0 1
  * forecast_time  (forecast_time) datetime64[ns] 2000-01-02 ... 2019-01-02
  * lead_time      (lead_time) timedelta64[ns] 1 days 2 days 3 days
  * latitude       (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * longitude      (longitude) float64 0.0 1.5 3.0 4.5 ... 355.5 357.0 358.5
    valid_time     (forecast_time, lead_time) datetime64[ns] dask.array<chunksize=(1, 1), meta=np.ndarray>
Data variables:
    tp             (realization, forecast_time, lead_time, latitude, longitude) float32 dask.array<chunksize=(1, 1, 1, 121, 240), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2021-04-14T16:01:25 GRIB to CDM+CF via cfgrib-0....

We can get the temperature parameter (2t) in a similar fashion. The "date" and "parameter" arguments also accept lists of values.

In [7]:
cml.load_dataset("s2s-ai-challenge-training-input",
                         origin='ecmwf',
                         date=20200102,
                         parameter='2t',
                         format=FORMAT).to_xarray()

<xarray.Dataset>
Dimensions:        (forecast_time: 20, latitude: 121, lead_time: 3, longitude: 240, realization: 2)
Coordinates:
  * realization    (realization) int64 0 1
  * forecast_time  (forecast_time) datetime64[ns] 2000-01-02 ... 2019-01-02
  * lead_time      (lead_time) timedelta64[ns] 2 days 3 days 4 days
  * latitude       (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * longitude      (longitude) float64 0.0 1.5 3.0 4.5 ... 355.5 357.0 358.5
    valid_time     (forecast_time, lead_time) datetime64[ns] dask.array<chunksize=(1, 1), meta=np.ndarray>
Data variables:
    t2m            (realization, forecast_time, lead_time, latitude, longitude) float32 dask.array<chunksize=(1, 1, 1, 121, 240), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2021-04-14T16:01:25 GRIB to CDM+CF via cfgrib-0....

In [8]:
#import numpy as np
#dates = [np.datetime64('2020-01-02'),'2020-01-09']#,'20200116']
#cml.load_dataset("s2s-ai-challenge-training-input",
#                 origin='eccc',
#                 date=dates,
#                 parameter=['2t','tp'],
#                 format=FORMAT).to_xarray()                 

Data from the forecast-input dataset can be retrieve in a similar fashion:

In [9]:
cml.load_dataset("s2s-ai-challenge-forecast-input",
                         origin='ecmwf',
                         date=["20200102","20200109"],
                         parameter='2t',
                         format=FORMAT).to_xarray()

By downloading data from this dataset, you agree to the terms and conditions defined at https://apps.ecmwf.int/datasets/data/s2s/licence/. If you do not agree with such terms, do not download the data. 


<xarray.Dataset>
Dimensions:        (forecast_time: 2, latitude: 121, lead_time: 3, longitude: 240, realization: 2)
Coordinates:
  * forecast_time  (forecast_time) datetime64[ns] 2020-01-02 2020-01-09
  * realization    (realization) int64 0 1
  * lead_time      (lead_time) timedelta64[ns] 2 days 3 days 4 days
  * latitude       (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * longitude      (longitude) float64 0.0 1.5 3.0 4.5 ... 355.5 357.0 358.5
    valid_time     (forecast_time, lead_time) datetime64[ns] dask.array<chunksize=(2, 1), meta=np.ndarray>
Data variables:
    t2m            (realization, forecast_time, lead_time, latitude, longitude) float32 dask.array<chunksize=(1, 2, 1, 121, 240), meta=np.ndarray>

### Computing average and plotting

In [10]:
ds = cml.load_dataset("s2s-ai-challenge-forecast-input",
                         origin='ecmwf',
                         date=["20200102","20200109"],
                         parameter='2t',
                         format=FORMAT).to_xarray()

In [11]:
mean1 = ds.mean(dim="lead_time")
mean1.compute()
#cml.plot_map(mean1.isel(forecast_time=0, realization=0))

<xarray.Dataset>
Dimensions:        (forecast_time: 2, latitude: 121, longitude: 240, realization: 2)
Coordinates:
  * forecast_time  (forecast_time) datetime64[ns] 2020-01-02 2020-01-09
  * realization    (realization) int64 0 1
  * latitude       (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * longitude      (longitude) float64 0.0 1.5 3.0 4.5 ... 355.5 357.0 358.5
Data variables:
    t2m            (realization, forecast_time, latitude, longitude) float32 ...

In [12]:
mean2 = ds.mean(dim="forecast_time")
mean2.compute()
#cml.plot_map(mean2.isel(lead_time=2, realization=0))

<xarray.Dataset>
Dimensions:      (latitude: 121, lead_time: 3, longitude: 240, realization: 2)
Coordinates:
  * realization  (realization) int64 0 1
  * lead_time    (lead_time) timedelta64[ns] 2 days 3 days 4 days
  * latitude     (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * longitude    (longitude) float64 0.0 1.5 3.0 4.5 ... 354.0 355.5 357.0 358.5
Data variables:
    t2m          (realization, lead_time, latitude, longitude) float32 247.1 ...

In [13]:
mean3 = ds[['t2m','valid_time']].groupby('valid_time').mean()['t2m']
mean3.compute()
# cml.plot_map(mean3.isel(forecast_time=2, realization=0))

<xarray.DataArray 't2m' (valid_time: 6, realization: 2, latitude: 121, longitude: 240)>
array([[[[246.9281 , 246.9281 , 246.9281 , ..., 246.9281 , 246.9281 ,
          246.9281 ],
         [246.25623, 246.2738 , 246.29138, ..., 246.17615, 246.20154,
          246.22888],
         [245.82654, 245.87146, 245.8949 , ..., 245.50037, 245.58044,
          245.70349],
         ...,
         [247.82458, 247.84412, 247.85388, ..., 247.66833, 247.7113 ,
          247.76599],
         [246.76013, 246.78357, 246.807  , ..., 246.71716, 246.73279,
          246.74646],
         [246.05505, 246.05505, 246.05505, ..., 246.05505, 246.05505,
          246.05505]],

        [[247.30017, 247.30017, 247.30017, ..., 247.30017, 247.30017,
          247.30017],
         [246.81384, 246.83728, 246.85876, ..., 246.70056, 246.73767,
          246.77478],
         [246.2826 , 246.31189, 246.32947, ..., 246.0033 , 246.07556,
          246.18103],
...
         [249.06335, 248.91101, 248.74304, ..., 249.60046, 249.40906,
          249.23328],
         [249.68835, 249.61414, 249.53992, ..., 249.9364 , 249.85437,
          249.77039],
         [249.87976, 249.87976, 249.87976, ..., 249.87976, 249.87976,
          249.87976]],

        [[245.33154, 245.33154, 245.33154, ..., 245.33154, 245.33154,
          245.33154],
         [244.81006, 244.85498, 244.8999 , ..., 244.61084, 244.67725,
          244.74365],
         [244.15771, 244.13428, 244.0835 , ..., 243.99951, 244.0581 ,
          244.10498],
         ...,
         [246.58936, 246.41943, 246.24365, ..., 247.18115, 246.97021,
          246.77881],
         [247.3628 , 247.25146, 247.14404, ..., 247.6792 , 247.57373,
          247.46826],
         [248.53271, 248.53271, 248.53271, ..., 248.53271, 248.53271,
          248.53271]]]], dtype=float32)
Coordinates:
  * realization  (realization) int64 0 1
  * latitude     (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * longitude    (longitude) float64 0.0 1.5 3.0 4.5 ... 354.0 355.5 357.0 358.5
  * valid_time   (valid_time) datetime64[ns] 2020-01-04 ... 2020-01-13